### ISSUE TITLE
Problem with Wifi Setup on RPi 0W

### ISSUE THREAD

**Issue by seprim** [hifiberry/hifiberry-os#151] opened 2020-10-18 13:20 UTC
Hello
I've installed the latest version of the OS on a RPi 0W and i'm not able to configure the wifi.
There is no Network available.

**Comment by hifiberry** [comment] 2020-10-19 11:44
Duplicate of https://github.com/hifiberry/hifiberry-os/issues/147

**Closed by hifiberry** 2020-10-19 11:44 UTC
Labels: duplicate
