### ISSUE TITLE
Sources - cannot activate Roon

### ISSUE THREAD

**Issue by jacobacci** [hifiberry/hifiberry-os#270] opened 2021-05-27 06:05 UTC
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
When I try to turn on Roon, it briefly appears in the group of active sources and then jumps to the group of disabled sources.
This is happening on two machines, both RP3B+, one DAC+ Pro, one DAC+ Light

**HiFiBerryOS version**
Software 20210521

**HiFiBerry sound card**
DAC+ Pro

**To Reproduce**
1. In Web GUI go to sources
2. Set Roon to on
3. Return to sources
4. Roon appears briefly in active sources, then the text moves to the disabled sources

**Expected behavior**
Roon should stay active

**Screenshots**

**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment] 2021-05-27 06:06
Duplicate of https://github.com/hifiberry/hifiberry-os/issues/269

**Closed by hifiberry** 2021-05-27 06:06 UTC
