### ISSUE TITLE
Web User Interface not working with power controller connected

### ISSUE THREAD

**Issue by Ferni-sl** [hifiberry/hifiberry-os#384] opened 2022-08-02 12:15 UTC
DO NOT remove the blocks below, but fill these with the requested data. Incomplete bug reports will be ignored!
You should remove this comment before posting the bug report.

**Describe the bug**
Description is available in this thread:
https://support.hifiberry.com/hc/en-us/community/posts/5136353031185-WEB-Interface-Playback-control-does-not-work-since-February-update

The web interface Volume slider, next-, previous-, play- and pause-button does not work on the web interface, when the power controller is connected.
When the power controller is disconnected, the web interface works well.

**HiFiBerryOS version**
20220228 and 20220726

**HiFiBerry sound card**
Amp100 + DSP Module + Power controller with firmware 0x05

Raspberry Pi 4 Model B Rev 1.2

**To Reproduce**
1. Switch on Hifiberry OS installation
2. connect with browser, no matter from which device or which browser
3. Start Musik (MPD) any album, stored on NAS file or Radio station (no other sources used) via browser
4. change volume via web UI slider does not work
5. skip title via web UI button does not work
6. previous title via web UI button does not work
7. play-/pause button via web UI does not work
8. Volume setting with power controller works
9. See error

**Expected behavior**
Web UI should work like it did before February update

**Screenshots**

**Browser (if applicable)**
 - Linux, Android, Windows
 - chrome, firefox, edge
 - Version: all

**Additional context**
When the power controller is disconnected (3 cables between power controller and Amp100), the web interface works well.
More information can be taken from the chat where I posted some listings as requested by your support team.

**Comment by hifiberry** [comment] 2022-08-04 07:39
Duplicate of https://github.com/hifiberry/hifiberry-os/issues/381

**Closed** 2022-08-04 07:39 UTC
Labels: duplicate
