### ISSUE TITLE
Spotify Connect not playing 

### ISSUE THREAD

**Issue by Gingso** [hifiberry/hifiberry-os#314] opened 2021-12-11 15:35 UTC
On my setup spotify connect is no longer working, even not after a downgrade to the August version:

Setup: 
20211105, PI-3b, DAC Pro

I can connect in Spotfify with hifiberry but sounds will played and the playing stops at the end of a song.

with journalctl i found the follwing events which may indicate an issue with alsa:

in Startup sequence:
Dec 11 16:25:22 hifiberry vollibrespot[555]: vollibrespot v0.2.2 UNKNOWN UNKNOWN (librespot 1a224a3 2020-10-25) -- Built On 2021-11-05
Dec 11 16:25:22 hifiberry vollibrespot[555]: Reading Config from "/etc/vollibrespot.conf"
Dec 11 16:25:22 hifiberry vollibrespot[555]: [Vollibrespot] : Using Alsa backend with device: default
Dec 11 16:25:22 hifiberry restore-volume[582]: alsactl: set_control:1461: Cannot write control '2:0:0:Max Overclock PLL:0' : Device or resource busy
Dec 11 16:25:22 hifiberry restore-volume[582]: alsactl: set_control:1461: Cannot write control '2:0:0:Max Overclock DSP:0' : Device or resource busy
Dec 11 16:25:22 hifiberry restore-volume[582]: alsactl: set_control:1461: Cannot write control '2:0:0:Max Overclock DAC:0' : Device or resource busy
Dec 11 16:25:22 hifiberry restore-volume[586]: Simple mixer control 'Softvol',0
Dec 11 16:25:22 hifiberry restore-volume[586]:   Capabilities: volume
Dec 11 16:25:22 hifiberry restore-volume[586]:   Playback channels: Front Left - Front Right
Dec 11 16:25:22 hifiberry restore-volume[586]:   Capture channels: Front Left - Front Right
Dec 11 16:25:22 hifiberry restore-volume[586]:   Limits: 0 - 255
Dec 11 16:25:22 hifiberry restore-volume[586]:   Front Left: 255 [100%]
Dec 11 16:25:22 hifiberry restore-volume[586]:   Front Right: 255 [100%]
Dec 11 16:25:23 hifiberry systemd[1]: Started Vollibrespot.

after connecting Spotify:
...
Dec 11 16:27:41 hifiberry vollibrespot[555]: [Vollibrespot] : <Song Title> (203480 ms) loaded
Dec 11 16:27:41 hifiberry /bin/cat[846]: pause-all vollibrespot (555): 20211211-162741 20211211-162741 vollibrespot - closed
Dec 11 16:27:41 hifiberry vollibrespot[555]: [Vollibrespot] : stopped other players
Dec 11 16:27:41 hifiberry vollibrespot[555]: [Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'EPERM: Operation not permitted'
Dec 11 16:27:41 hifiberry vollibrespot[555]: [Vollibrespot] : Could not start audio: Alsa error: PCM open failed
Dec 11 16:27:42 hifiberry /bin/cat[871]: pause-all vollibrespot (555): requested pause, but is already using sound card, ignoring
Dec 11 16:27:42 hifiberry vollibrespot[555]: [Vollibrespot] : stopped other players
Dec 11 16:27:42 hifiberry vollibrespot[555]: [Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'EBUSY: Device or resource busy'
Dec 11 16:27:42 hifiberry vollibrespot[555]: [Vollibrespot] : Could not start audio: Alsa error: PCM open failed
Dec 11 16:27:42 hifiberry /bin/cat[893]: pause-all vollibrespot (555): requested pause, but is already using sound card, ignoring
Dec 11 16:27:42 hifiberry vollibrespot[555]: [Vollibrespot] : stopped other players
Dec 11 16:27:42 hifiberry vollibrespot[555]: [Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'EBUSY: Device or resource busy'
Dec 11 16:27:42 hifiberry vollibrespot[555]: [Vollibrespot] : Could not start audio: Alsa error: PCM open failed
Dec 11 16:27:42 hifiberry vollibrespot[555]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/matuschd/buildroot-3/host/share/cargo/git/checkouts/librespot-e4d7c35a023053af/1a224a3/playback/src/audio_backend/alsa.rs:138:35
Dec 11 16:27:42 hifiberry vollibrespot[555]: stack backtrace:
Dec 11 16:27:42 hifiberry vollibrespot[555]:    0:   0x9dc770 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    1:   0xa01b20 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    2:   0x9d4b98 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    3:   0x9def28 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    4:   0x9de8c0 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    5:   0x9df588 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    6:   0x9df0cc - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    7:   0x9dccec - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    8:   0x9df04c - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:    9:   0x4aa6ac - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   10:   0x4aa608 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   11:   0x5ee294 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   12:   0x5cb444 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   13:   0x4eb770 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   14:   0x4d75a8 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   15:   0x4fd220 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   16:   0x50810c - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   17:   0x4f7324 - <unknown>
Dec 11 16:27:42 hifiberry vollibrespot[555]:   18:   0x9e5cf8 - <unknown>

anyone  an idea howto fix this?

Best
 Oliver

**Comment by hifiberry** [comment] 2022-01-13 08:03
Duplicate of https://github.com/hifiberry/hifiberry-os/issues/312

**Closed by hifiberry** 2022-01-13 08:03 UTC
