### ISSUE TITLE
Radio can't be stopped, other sources won't play

### ISSUE THREAD

**Issue by Thornild2** [hifiberry/hifiberry-os#176] opened 2020-11-08 14:02 UTC
**Describe the bug**
When using the radio featur no other source will play, and the radio cannot be stopped.   

**HiFiBerryOS version**
Software 20201101

**HiFiBerry sound card**
Beocreate 4-Channel Amplifier

**To Reproduce**
1. Go to sources
2. Click on radio and select station
4. Radio will play and cannot be stopped

**Expected behavior**
The radio should play when selected, and switch to other sources if they are selected.

**Additional context**
If I switch to another radio station, spotify might start playing if that is the source i am trying to play from. This was not af problem in earlyer releases.

**Comment by hifiberry** [comment] 2020-11-08 14:20
Duplicate of https://github.com/hifiberry/hifiberry-os/issues/157

**Closed by hifiberry** 2020-11-08 14:20 UTC
Labels: duplicate
