### ISSUE TITLE
Switching from one service renderer to another often fails

### ISSUE THREAD

**Issue by schmurtzm** [hifiberry/hifiberry-os#326] opened 2022-01-11 16:25 UTC
**Describe the bug**
Switching from Spotify Connect to Airplay doesn't work (and even seems to crash airplay service -> need to restart airplay service to use it again).
You can extend this problem to many case when you switch between renderers  : i.e. : trying to switch from Squeezelite to Spotify Connect  doesn't work.

**HiFiBerryOS version**
20211105

**HiFiBerry sound card**
HiFiBerry DAC+ standard – RCA version

**To Reproduce**
1- on IOS play with spotify connect
2 - switch directly to airplay (from spotify connect or any other app)

**Expected behavior**
HifiBerryos should detect and incoming play, stop the previous renderer before launching play on the next render.
We also could imagine an option in web interface to authorise or not renderer overriding.

**Screenshots**

**Browser (if applicable)**
 - IOS 15 / Iphone 8 (same behavior from a PC)

**Additional context**
[One way to manage it between shairport and squeezelite](https://www.max2play.com/en/forums/topic/squeezelite-and-shairport-together-on-blocking-dac/)

Thanks this this great audio player ;)

**Comment by hifiberry** [comment] 2022-01-13 08:03
Duplicate of https://github.com/hifiberry/hifiberry-os/issues/312

**Closed by hifiberry** 2022-01-13 08:03 UTC

**Comment by schmurtzm** [comment] 2022-01-16 14:19
I confirm : works very well after removing the quotes ;)
